/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as AuthenticatedHowToRouteImport } from './routes/_authenticated/how-to'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SlugSubmitRouteImport } from './routes/$slug.submit'
import { Route as SlugRotateRouteImport } from './routes/$slug.rotate'
import { Route as SlugHoleInOnesRouteImport } from './routes/$slug.hole-in-ones'
import { Route as SlugEmbedRouteImport } from './routes/$slug.embed'
import { Route as SlugDisplayRouteImport } from './routes/$slug.display'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicHeartbeatRouteImport } from './routes/api/public/heartbeat'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminManageRouteImport } from './routes/_authenticated/admin.manage'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminEntriesRouteImport } from './routes/_authenticated/admin.entries'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as SlugHoleHoleNumberRouteImport } from './routes/$slug.hole.$holeNumber'
import { Route as SlugEntryEntryIdRouteImport } from './routes/$slug.entry.$entryId'
import { Route as ApiPublicE2eBootstrapRouteImport } from './routes/api/public/e2e/bootstrap'
import { Route as AuthenticatedAdminCourseCourseIdRouteImport } from './routes/_authenticated/admin.course.$courseId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHowToRoute = AuthenticatedHowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SlugSubmitRoute = SlugSubmitRouteImport.update({
  id: '/$slug/submit',
  path: '/$slug/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRotateRoute = SlugRotateRouteImport.update({
  id: '/$slug/rotate',
  path: '/$slug/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugHoleInOnesRoute = SlugHoleInOnesRouteImport.update({
  id: '/$slug/hole-in-ones',
  path: '/$slug/hole-in-ones',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugEmbedRoute = SlugEmbedRouteImport.update({
  id: '/$slug/embed',
  path: '/$slug/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugDisplayRoute = SlugDisplayRouteImport.update({
  id: '/$slug/display',
  path: '/$slug/display',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHeartbeatRoute = ApiPublicHeartbeatRouteImport.update({
  id: '/api/public/heartbeat',
  path: '/api/public/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManageRoute =
  AuthenticatedAdminManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntriesRoute =
  AuthenticatedAdminEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SlugHoleHoleNumberRoute = SlugHoleHoleNumberRouteImport.update({
  id: '/$slug/hole/$holeNumber',
  path: '/$slug/hole/$holeNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugEntryEntryIdRoute = SlugEntryEntryIdRouteImport.update({
  id: '/$slug/entry/$entryId',
  path: '/$slug/entry/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicE2eBootstrapRoute = ApiPublicE2eBootstrapRouteImport.update({
  id: '/api/public/e2e/bootstrap',
  path: '/api/public/e2e/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCourseCourseIdRoute =
  AuthenticatedAdminCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/display': typeof SlugDisplayRoute
  '/$slug/embed': typeof SlugEmbedRoute
  '/$slug/hole-in-ones': typeof SlugHoleInOnesRoute
  '/$slug/rotate': typeof SlugRotateRoute
  '/$slug/submit': typeof SlugSubmitRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/how-to': typeof AuthenticatedHowToRoute
  '/api/tutor': typeof ApiTutorRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/$slug/entry/$entryId': typeof SlugEntryEntryIdRoute
  '/$slug/hole/$holeNumber': typeof SlugHoleHoleNumberRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/entries': typeof AuthenticatedAdminEntriesRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/manage': typeof AuthenticatedAdminManageRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/course/$courseId': typeof AuthenticatedAdminCourseCourseIdRoute
  '/api/public/e2e/bootstrap': typeof ApiPublicE2eBootstrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/display': typeof SlugDisplayRoute
  '/$slug/embed': typeof SlugEmbedRoute
  '/$slug/hole-in-ones': typeof SlugHoleInOnesRoute
  '/$slug/rotate': typeof SlugRotateRoute
  '/$slug/submit': typeof SlugSubmitRoute
  '/how-to': typeof AuthenticatedHowToRoute
  '/api/tutor': typeof ApiTutorRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/$slug/entry/$entryId': typeof SlugEntryEntryIdRoute
  '/$slug/hole/$holeNumber': typeof SlugHoleHoleNumberRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/entries': typeof AuthenticatedAdminEntriesRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/manage': typeof AuthenticatedAdminManageRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/course/$courseId': typeof AuthenticatedAdminCourseCourseIdRoute
  '/api/public/e2e/bootstrap': typeof ApiPublicE2eBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/display': typeof SlugDisplayRoute
  '/$slug/embed': typeof SlugEmbedRoute
  '/$slug/hole-in-ones': typeof SlugHoleInOnesRoute
  '/$slug/rotate': typeof SlugRotateRoute
  '/$slug/submit': typeof SlugSubmitRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/how-to': typeof AuthenticatedHowToRoute
  '/api/tutor': typeof ApiTutorRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/$slug/entry/$entryId': typeof SlugEntryEntryIdRoute
  '/$slug/hole/$holeNumber': typeof SlugHoleHoleNumberRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/entries': typeof AuthenticatedAdminEntriesRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/manage': typeof AuthenticatedAdminManageRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/course/$courseId': typeof AuthenticatedAdminCourseCourseIdRoute
  '/api/public/e2e/bootstrap': typeof ApiPublicE2eBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/$slug/display'
    | '/$slug/embed'
    | '/$slug/hole-in-ones'
    | '/$slug/rotate'
    | '/$slug/submit'
    | '/admin'
    | '/how-to'
    | '/api/tutor'
    | '/invitation/$token'
    | '/unsubscribe/$token'
    | '/$slug/entry/$entryId'
    | '/$slug/hole/$holeNumber'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/entries'
    | '/admin/health'
    | '/admin/import'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/api/public/heartbeat'
    | '/admin/'
    | '/admin/course/$courseId'
    | '/api/public/e2e/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/$slug/display'
    | '/$slug/embed'
    | '/$slug/hole-in-ones'
    | '/$slug/rotate'
    | '/$slug/submit'
    | '/how-to'
    | '/api/tutor'
    | '/invitation/$token'
    | '/unsubscribe/$token'
    | '/$slug/entry/$entryId'
    | '/$slug/hole/$holeNumber'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/entries'
    | '/admin/health'
    | '/admin/import'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/api/public/heartbeat'
    | '/admin'
    | '/admin/course/$courseId'
    | '/api/public/e2e/bootstrap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/$slug/display'
    | '/$slug/embed'
    | '/$slug/hole-in-ones'
    | '/$slug/rotate'
    | '/$slug/submit'
    | '/_authenticated/admin'
    | '/_authenticated/how-to'
    | '/api/tutor'
    | '/invitation/$token'
    | '/unsubscribe/$token'
    | '/$slug/entry/$entryId'
    | '/$slug/hole/$holeNumber'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/entries'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/manage'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscribers'
    | '/api/public/heartbeat'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/course/$courseId'
    | '/api/public/e2e/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SlugDisplayRoute: typeof SlugDisplayRoute
  SlugEmbedRoute: typeof SlugEmbedRoute
  SlugHoleInOnesRoute: typeof SlugHoleInOnesRoute
  SlugRotateRoute: typeof SlugRotateRoute
  SlugSubmitRoute: typeof SlugSubmitRoute
  ApiTutorRoute: typeof ApiTutorRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  SlugEntryEntryIdRoute: typeof SlugEntryEntryIdRoute
  SlugHoleHoleNumberRoute: typeof SlugHoleHoleNumberRoute
  ApiPublicHeartbeatRoute: typeof ApiPublicHeartbeatRoute
  ApiPublicE2eBootstrapRoute: typeof ApiPublicE2eBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/how-to': {
      id: '/_authenticated/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof AuthenticatedHowToRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$slug/submit': {
      id: '/$slug/submit'
      path: '/$slug/submit'
      fullPath: '/$slug/submit'
      preLoaderRoute: typeof SlugSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/rotate': {
      id: '/$slug/rotate'
      path: '/$slug/rotate'
      fullPath: '/$slug/rotate'
      preLoaderRoute: typeof SlugRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/hole-in-ones': {
      id: '/$slug/hole-in-ones'
      path: '/$slug/hole-in-ones'
      fullPath: '/$slug/hole-in-ones'
      preLoaderRoute: typeof SlugHoleInOnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/embed': {
      id: '/$slug/embed'
      path: '/$slug/embed'
      fullPath: '/$slug/embed'
      preLoaderRoute: typeof SlugEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/display': {
      id: '/$slug/display'
      path: '/$slug/display'
      fullPath: '/$slug/display'
      preLoaderRoute: typeof SlugDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/heartbeat': {
      id: '/api/public/heartbeat'
      path: '/api/public/heartbeat'
      fullPath: '/api/public/heartbeat'
      preLoaderRoute: typeof ApiPublicHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manage': {
      id: '/_authenticated/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AuthenticatedAdminManageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entries': {
      id: '/_authenticated/admin/entries'
      path: '/entries'
      fullPath: '/admin/entries'
      preLoaderRoute: typeof AuthenticatedAdminEntriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/$slug/hole/$holeNumber': {
      id: '/$slug/hole/$holeNumber'
      path: '/$slug/hole/$holeNumber'
      fullPath: '/$slug/hole/$holeNumber'
      preLoaderRoute: typeof SlugHoleHoleNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/entry/$entryId': {
      id: '/$slug/entry/$entryId'
      path: '/$slug/entry/$entryId'
      fullPath: '/$slug/entry/$entryId'
      preLoaderRoute: typeof SlugEntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/e2e/bootstrap': {
      id: '/api/public/e2e/bootstrap'
      path: '/api/public/e2e/bootstrap'
      fullPath: '/api/public/e2e/bootstrap'
      preLoaderRoute: typeof ApiPublicE2eBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/course/$courseId': {
      id: '/_authenticated/admin/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/admin/course/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCourseCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminEntriesRoute: typeof AuthenticatedAdminEntriesRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminManageRoute: typeof AuthenticatedAdminManageRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCourseCourseIdRoute: typeof AuthenticatedAdminCourseCourseIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminEntriesRoute: AuthenticatedAdminEntriesRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminManageRoute: AuthenticatedAdminManageRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCourseCourseIdRoute: AuthenticatedAdminCourseCourseIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHowToRoute: typeof AuthenticatedHowToRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHowToRoute: AuthenticatedHowToRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SlugDisplayRoute: SlugDisplayRoute,
  SlugEmbedRoute: SlugEmbedRoute,
  SlugHoleInOnesRoute: SlugHoleInOnesRoute,
  SlugRotateRoute: SlugRotateRoute,
  SlugSubmitRoute: SlugSubmitRoute,
  ApiTutorRoute: ApiTutorRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  SlugEntryEntryIdRoute: SlugEntryEntryIdRoute,
  SlugHoleHoleNumberRoute: SlugHoleHoleNumberRoute,
  ApiPublicHeartbeatRoute: ApiPublicHeartbeatRoute,
  ApiPublicE2eBootstrapRoute: ApiPublicE2eBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
